# Generated by Django 5.1.4 on 2025-01-10 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LiveFaceGuard', '0002_alert'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
