# Generated by Django 5.1.4 on 2025-01-12 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LiveFaceGuard', '0003_detect'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Detect',
        ),
    ]
