# Generated by Django 5.1.4 on 2025-01-12 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LiveFaceGuard', '0004_delete_detect'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveFaceGuard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
