# Generated by Django 5.1.4 on 2025-01-12 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LiveFaceGuard', '0005_livefaceguard'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Alert',
        ),
    ]
